import { createHash } from "node:crypto";
import path from "node:path";
import { resolveReferences } from "./reference-resolver.js";
import type {
  AuditFinding,
  AuditFindingKind,
  AuditHeuristics,
  AuditReport,
  VaultInventory,
  VaultNote,
} from "./types.js";

export interface AuditOptions {
  oversizedBytes?: number;
  oversizedLines?: number;
  staleAfterDays?: number;
  nearDuplicateThreshold?: number;
  nearDuplicateMinimumCharacters?: number;
  nearDuplicateMinimumLengthRatio?: number;
  now?: Date;
}

const INDEX_VARIANTS = new Set([
  "index.md",
  "_index.md",
  "home.md",
  "readme.md",
]);

const STALE_STATE_TASK_NAMES = [
  "state.md",
  "tasks.md",
  "task.md",
  "todo.md",
];

/** Produces a stable finding identifier from its semantic identity instead of array position. */
function findingId(
  kind: AuditFindingKind,
  paths: string[],
  reason: string,
): string {
  return createHash("sha256")
    .update(
      `${kind}\n${[...paths]
        .sort()
        .join("\n")}\n${reason}`,
    )
    .digest("hex")
    .slice(0, 16);
}

/** Creates an audit finding with deterministic path ordering and identifier generation. */
function finding(
  input: Omit<AuditFinding, "id">,
): AuditFinding {
  const paths = [...input.paths].sort();

  return {
    ...input,
    paths,
    id: findingId(
      input.kind,
      paths,
      input.reason,
    ),
  };
}

/** Converts a note body into normalized word tokens suitable for conservative near-duplicate comparison. */
function tokenize(body: string): string[] {
  return body
    .toLowerCase()
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`[^`]*`/g, " ")
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .trim()
    .split(/\s+/)
    .filter((token) => token.length >= 2);
}

/** Builds fixed-size token shingles so similarity reflects phrase overlap rather than only shared vocabulary. */
function shingles(
  tokens: string[],
  size: number,
): Set<string> {
  const result = new Set<string>();

  for (
    let index = 0;
    index <= tokens.length - size;
    index += 1
  ) {
    result.add(
      tokens
        .slice(index, index + size)
        .join(" "),
    );
  }

  return result;
}

/** Computes Jaccard similarity between two shingle sets. */
function jaccard(
  left: Set<string>,
  right: Set<string>,
): number {
  if (
    left.size === 0 ||
    right.size === 0
  ) {
    return 0;
  }

  let intersection = 0;

  for (const value of left) {
    if (right.has(value)) {
      intersection += 1;
    }
  }

  return (
    intersection /
    (left.size +
      right.size -
      intersection)
  );
}

/** Normalizes note titles and aliases into conservative authority keys. */
function authorityKey(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFKC")
    .replace(
      /[^\p{L}\p{N}]+/gu,
      " ",
    )
    .trim();
}

/** Detects generated-output evidence and returns the exact transparent reasons that matched. */
function generatedReasons(
  note: VaultNote,
): string[] {
  const reasons: string[] = [];

  const segments = note.path
    .toLowerCase()
    .split("/");

  const basename = path.posix
    .basename(note.path)
    .toLowerCase();

  const frontmatter =
    note.frontmatter.data;

  const firstLines = note.body
    .split(/\r?\n/)
    .slice(0, 8)
    .join("\n")
    .toLowerCase();

  if (
    frontmatter.generated === true ||
    frontmatter.ai_generated === true ||
    frontmatter.generated_output === true
  ) {
    reasons.push(
      "frontmatter explicitly marks the note as generated",
    );
  }

  if (
    segments.some((segment) =>
      [
        "generated",
        "generated-output",
        "generated-outputs",
      ].includes(segment),
    )
  ) {
    reasons.push(
      "path is inside an explicitly generated-output directory",
    );
  }

  if (
    /(?:^|[-_.])generated(?:[-_.]|\.md$)/.test(
      basename,
    )
  ) {
    reasons.push(
      "filename explicitly contains a generated marker",
    );
  }

  if (
    /generated by|auto-generated|autogenerated/.test(
      firstLines,
    )
  ) {
    reasons.push(
      "opening content contains an explicit generated marker",
    );
  }

  return reasons;
}

/** Builds the read-only audit report from an already parsed inventory. */
export function auditInventory(
  inventory: VaultInventory,
  options: AuditOptions = {},
): AuditReport {
  const oversizedBytes =
    options.oversizedBytes ??
    64 * 1024;

  const oversizedLines =
    options.oversizedLines ?? 1200;

  const staleAfterDays =
    options.staleAfterDays ?? 45;

  const nearDuplicateThreshold =
    options.nearDuplicateThreshold ??
    0.88;

  const nearDuplicateMinimumCharacters =
    options.nearDuplicateMinimumCharacters ??
    500;

  const nearDuplicateMinimumLengthRatio =
    options.nearDuplicateMinimumLengthRatio ??
    0.8;

  const now = options.now ?? new Date();
  const shingleSize = 5;

  const findings: AuditFinding[] = [];
  const resolutions =
    resolveReferences(inventory);

  const allFiles = [
    ...inventory.notes.map((item) => ({
      path: item.path,
      hash: item.hash,
      kind: item.kind,
    })),
    ...inventory.assets.map((item) => ({
      path: item.path,
      hash: item.hash,
      kind: item.kind,
    })),
    ...inventory.canvases.map(
      (item) => ({
        path: item.path,
        hash: item.hash,
        kind: item.kind,
      }),
    ),
  ];

  const byHash = new Map<
    string,
    Array<{
      path: string;
      kind: string;
    }>
  >();

  for (const item of allFiles) {
    byHash.set(item.hash, [
      ...(byHash.get(item.hash) ?? []),
      {
        path: item.path,
        kind: item.kind,
      },
    ]);
  }

  for (const [hash, items] of byHash) {
    if (items.length < 2) {
      continue;
    }

    findings.push(
      finding({
        kind: "exact-duplicate",
        confidence: "high",
        severity: "warning",
        paths: items.map(
          (item) => item.path,
        ),
        reason:
          `Files have identical raw SHA-256 content hash ${hash}.`,
        details: {
          hash,
          kinds: items.map(
            (item) => item.kind,
          ),
        },
      }),
    );
  }

  const nearCandidates =
    inventory.notes
      .filter(
        (note) =>
          note.body.trim().length >=
          nearDuplicateMinimumCharacters,
      )
      .map((note) => {
        const tokens =
          tokenize(note.body);

        return {
          note,
          shingles: shingles(
            tokens,
            shingleSize,
          ),
        };
      });

  for (
    let leftIndex = 0;
    leftIndex < nearCandidates.length;
    leftIndex += 1
  ) {
    for (
      let rightIndex =
        leftIndex + 1;
      rightIndex <
      nearCandidates.length;
      rightIndex += 1
    ) {
      const left =
        nearCandidates[leftIndex];

      const right =
        nearCandidates[rightIndex];

      if (
        left.note.hash ===
        right.note.hash
      ) {
        continue;
      }

      const lengthRatio =
        Math.min(
          left.note.body.length,
          right.note.body.length,
        ) /
        Math.max(
          left.note.body.length,
          right.note.body.length,
        );

      if (
        lengthRatio <
        nearDuplicateMinimumLengthRatio
      ) {
        continue;
      }

      const similarity = jaccard(
        left.shingles,
        right.shingles,
      );

      if (
        similarity >=
        nearDuplicateThreshold
      ) {
        findings.push(
          finding({
            kind: "near-duplicate",
            confidence: "medium",
            severity: "warning",
            paths: [
              left.note.path,
              right.note.path,
            ],
            reason:
              `Normalized ${shingleSize}-token shingle Jaccard similarity is ` +
              `${similarity.toFixed(3)}, at or above ${nearDuplicateThreshold}.`,
            details: {
              similarity,
              lengthRatio,
              shingleSize,
              threshold:
                nearDuplicateThreshold,
            },
          }),
        );
      }
    }
  }

  for (const resolution of resolutions) {
    if (
      resolution.status === "broken"
    ) {
      findings.push(
        finding({
          kind: "broken-reference",
          confidence: "high",
          severity: "error",
          paths: [
            resolution.reference
              .sourcePath,
          ],
          reason: resolution.reason,
          details: {
            reference:
              resolution.reference,
            attemptedCandidates:
              resolution.candidates,
            resolvedPath:
              resolution.resolvedPath,
          },
        }),
      );
    } else if (
      resolution.status ===
      "case-mismatch"
    ) {
      findings.push(
        finding({
          kind:
            "reference-case-mismatch",
          confidence: "high",
          severity: "warning",
          paths: [
            resolution.reference
              .sourcePath,
            ...(resolution.resolvedPath
              ? [
                  resolution.resolvedPath,
                ]
              : []),
          ],
          reason: resolution.reason,
          details: {
            reference:
              resolution.reference,
            resolvedPath:
              resolution.resolvedPath,
          },
        }),
      );
    } else if (
      resolution.status ===
      "ambiguous"
    ) {
      findings.push(
        finding({
          kind: "authority-conflict",
          confidence: "medium",
          severity: "warning",
          paths: [
            resolution.reference
              .sourcePath,
            ...resolution.candidates,
          ],
          reason: resolution.reason,
          details: {
            reference:
              resolution.reference,
            candidates:
              resolution.candidates,
          },
        }),
      );
    }
  }

  const inboundCounts =
    new Map<string, number>();

  for (const item of allFiles) {
    inboundCounts.set(item.path, 0);
  }

  for (const resolution of resolutions) {
    if (
      (resolution.status ===
        "resolved" ||
        resolution.status ===
          "case-mismatch") &&
      resolution.resolvedPath
    ) {
      inboundCounts.set(
        resolution.resolvedPath,
        (inboundCounts.get(
          resolution.resolvedPath,
        ) ?? 0) + 1,
      );
    }
  }

  for (const note of inventory.notes) {
    if (
      (inboundCounts.get(note.path) ??
        0) === 0
    ) {
      findings.push(
        finding({
          kind: "orphan-note",
          confidence: "low",
          severity: "info",
          paths: [note.path],
          reason:
            "No resolved Markdown, wikilink, embed, or Canvas reference points to this note.",
          details: {
            outboundReferences:
              note.references.length,
          },
        }),
      );
    }
  }

  for (const asset of inventory.assets) {
    if (
      (inboundCounts.get(
        asset.path,
      ) ?? 0) === 0
    ) {
      findings.push(
        finding({
          kind: "orphan-asset",
          confidence: "medium",
          severity: "info",
          paths: [asset.path],
          reason:
            "No resolved Markdown, embed, or Canvas reference points to this asset.",
          details: {
            sizeBytes:
              asset.sizeBytes,
          },
        }),
      );
    }
  }

  const indexesByDirectory =
    new Map<string, string[]>();

  for (const note of inventory.notes) {
    const basename = path.posix
      .basename(note.path)
      .toLowerCase();

    if (
      !INDEX_VARIANTS.has(basename)
    ) {
      continue;
    }

    const directory =
      path.posix.dirname(note.path);

    indexesByDirectory.set(
      directory,
      [
        ...(indexesByDirectory.get(
          directory,
        ) ?? []),
        note.path,
      ],
    );
  }

  for (
    const [
      directory,
      paths,
    ] of indexesByDirectory
  ) {
    if (paths.length > 1) {
      findings.push(
        finding({
          kind:
            "duplicate-index-variant",
          confidence: "high",
          severity: "warning",
          paths,
          reason:
            `Directory ${directory} contains multiple index-style note variants.`,
          details: {
            directory,
            recognizedNames: [
              ...INDEX_VARIANTS,
            ],
          },
        }),
      );
    }
  }

  for (const note of inventory.notes) {
    if (
      note.sizeBytes >
        oversizedBytes ||
      note.lineCount >
        oversizedLines
    ) {
      findings.push(
        finding({
          kind: "oversized-note",
          confidence: "high",
          severity: "info",
          paths: [note.path],
          reason:
            "Note exceeds configured size or line threshold.",
          details: {
            sizeBytes:
              note.sizeBytes,
            lineCount:
              note.lineCount,
            oversizedBytes,
            oversizedLines,
          },
        }),
      );
    }

    const generated =
      generatedReasons(note);

    if (generated.length > 0) {
      findings.push(
        finding({
          kind:
            "generated-output-candidate",
          confidence:
            generated.length >= 2
              ? "high"
              : "medium",
          severity: "info",
          paths: [note.path],
          reason:
            generated.join("; "),
          details: {
            matchedSignals:
              generated,
          },
        }),
      );
    }

    const basename = path.posix
      .basename(note.path)
      .toLowerCase();

    if (
      STALE_STATE_TASK_NAMES.includes(
        basename,
      )
    ) {
      const ageDays = Math.floor(
        (now.getTime() -
          note.mtimeMs) /
          86_400_000,
      );

      if (
        ageDays >= staleAfterDays
      ) {
        findings.push(
          finding({
            kind:
              "stale-state-task-candidate",
            confidence: "medium",
            severity: "info",
            paths: [note.path],
            reason:
              `${basename} has not been modified for approximately ` +
              `${ageDays} days, exceeding the ${staleAfterDays}-day threshold.`,
            details: {
              ageDays,
              staleAfterDays,
              mtimeMs:
                note.mtimeMs,
            },
          }),
        );
      }
    }
  }

  const authorityMap =
    new Map<string, Set<string>>();

  for (const note of inventory.notes) {
    const values = [
      path.posix.basename(
        note.path,
        ".md",
      ),
    ];

    const title =
      note.frontmatter.data.title;

    if (
      typeof title === "string" &&
      title.trim()
    ) {
      values.push(title);
    }

    values.push(...note.aliases);

    for (const value of values) {
      const key =
        authorityKey(value);

      if (!key) {
        continue;
      }

      const paths =
        authorityMap.get(key) ??
        new Set<string>();

      paths.add(note.path);
      authorityMap.set(
        key,
        paths,
      );
    }
  }

  for (
    const [key, paths] of
    authorityMap
  ) {
    if (paths.size > 1) {
      findings.push(
        finding({
          kind: "authority-conflict",
          confidence: "medium",
          severity: "warning",
          paths: [...paths],
          reason:
            `Multiple notes claim the normalized title or alias authority key "${key}".`,
          details: {
            authorityKey: key,
          },
        }),
      );
    }
  }

  const byKind: Partial<
    Record<AuditFindingKind, number>
  > = {};

  for (const item of findings) {
    byKind[item.kind] =
      (byKind[item.kind] ?? 0) + 1;
  }

  const heuristics: AuditHeuristics = {
    exactDuplicates:
      "Raw file bytes must share the same SHA-256 hash.",
    nearDuplicates: {
      minimumBodyCharacters:
        nearDuplicateMinimumCharacters,
      minimumLengthRatio:
        nearDuplicateMinimumLengthRatio,
      minimumJaccardSimilarity:
        nearDuplicateThreshold,
      shingleSize,
    },
    oversizedNotes: {
      maxBytes: oversizedBytes,
      maxLines: oversizedLines,
    },
    staleStateTasks: {
      staleAfterDays,
      matchedBasenames:
        STALE_STATE_TASK_NAMES,
    },
    generatedOutputCandidates: [
      "explicit generated frontmatter flag",
      "explicit generated-output directory",
      "generated filename marker",
      "generated marker in opening content",
    ],
    authorityConflicts:
      "Normalized note basenames, frontmatter title, and aliases are compared across distinct notes.",
  };

  findings.sort(
    (left, right) =>
      left.kind.localeCompare(
        right.kind,
      ) ||
      left.paths
        .join("\n")
        .localeCompare(
          right.paths.join("\n"),
        ),
  );

  return {
    schemaVersion: 1,
    generatedAt:
      now.toISOString(),
    vaultRoot:
      inventory.vaultRoot,
    heuristics,
    summary: {
      notes:
        inventory.notes.length,
      assets:
        inventory.assets.length,
      canvases:
        inventory.canvases.length,
      warnings:
        inventory.warnings.length,
      findings:
        findings.length,
      byKind,
    },
    findings,
  };
}
